server:
  port: 9999

spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  thymeleaf:
          prefix: classpath:/static/
          suffix: .html
          cache: false 
  
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 8
        max-idle: 0
      shutdown-timeout: 10000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ticket?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123

mybatis:
  type-aliases-package: com.ticketsystem.entity

logging:
  level:
    com.ticketsystem: debug
#  file: ./log/info.log
  file: E:/info.log
  root: INFO
